name: Sync with upstream

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/JFLXCLOUD/NeXroll.git
          git fetch upstream
          DEFAULT_BRANCH=$(git remote show upstream | grep 'HEAD branch' | cut -d' ' -f5)
          echo "Upstream default branch is: $DEFAULT_BRANCH"
          git checkout $DEFAULT_BRANCH
          git merge upstream/$DEFAULT_BRANCH --ff-only
          git push origin $DEFAULT_BRANCH
